#pragma once
#include "common.h"

void mesh_sendA(hls::stream<uop_mesh_sendA_type> &stream_uOP_mesh_sendA,

                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A0_CASC0,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A0_CASC1,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A0_CASC2,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A0_CASC3,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A1_CASC0,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A1_CASC1,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A1_CASC2,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A1_CASC3,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A2_CASC0,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A2_CASC1,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A2_CASC2,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A2_CASC3,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A3_CASC0,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A3_CASC1,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A3_CASC2,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_A3_CASC3,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A0_CASC0,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A0_CASC1,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A0_CASC2,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A0_CASC3,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A1_CASC0,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A1_CASC1,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A1_CASC2,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A1_CASC3,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A2_CASC0,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A2_CASC1,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A2_CASC2,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A2_CASC3,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A3_CASC0,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A3_CASC1,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A3_CASC2,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_A3_CASC3,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A0_CASC0,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A0_CASC1,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A0_CASC2,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A0_CASC3,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A1_CASC0,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A1_CASC1,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A1_CASC2,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A1_CASC3,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A2_CASC0,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A2_CASC1,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A2_CASC2,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A2_CASC3,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A3_CASC0,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A3_CASC1,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A3_CASC2,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_A3_CASC3,

                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C0_CASC0,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C0_CASC1,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C0_CASC2,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C0_CASC3,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C1_CASC0,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C1_CASC1,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C1_CASC2,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C1_CASC3,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C2_CASC0,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C2_CASC1,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C2_CASC2,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C2_CASC3,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C3_CASC0,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C3_CASC1,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C3_CASC2,
                hls::stream<ap_uint<64>> &from_memCore0_to_mesh_C3_CASC3,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C0_CASC0,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C0_CASC1,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C0_CASC2,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C0_CASC3,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C1_CASC0,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C1_CASC1,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C1_CASC2,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C1_CASC3,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C2_CASC0,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C2_CASC1,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C2_CASC2,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C2_CASC3,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C3_CASC0,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C3_CASC1,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C3_CASC2,
                hls::stream<ap_uint<64>> &from_memCore1_to_mesh_C3_CASC3,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C0_CASC0,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C0_CASC1,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C0_CASC2,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C0_CASC3,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C1_CASC0,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C1_CASC1,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C1_CASC2,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C1_CASC3,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C2_CASC0,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C2_CASC1,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C2_CASC2,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C2_CASC3,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C3_CASC0,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C3_CASC1,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C3_CASC2,
                hls::stream<ap_uint<64>> &from_memCore2_to_mesh_C3_CASC3,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C0_CASC0,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C0_CASC1,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C0_CASC2,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C0_CASC3,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C1_CASC0,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C1_CASC1,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C1_CASC2,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C1_CASC3,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C2_CASC0,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C2_CASC1,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C2_CASC2,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C2_CASC3,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C3_CASC0,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C3_CASC1,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C3_CASC2,
                hls::stream<ap_uint<64>> &from_memCore3_to_mesh_C3_CASC3,

                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A0_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A0_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A0_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A0_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A1_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A1_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A1_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A1_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A2_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A2_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A2_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A2_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A3_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A3_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A3_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore0_A3_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A0_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A0_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A0_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A0_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A1_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A1_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A1_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A1_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A2_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A2_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A2_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A2_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A3_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A3_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A3_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore1_A3_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A0_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A0_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A0_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A0_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A1_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A1_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A1_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A1_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A2_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A2_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A2_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A2_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A3_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A3_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A3_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore2_A3_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A0_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A0_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A0_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A0_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A1_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A1_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A1_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A1_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A2_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A2_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A2_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A2_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A3_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A3_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A3_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore3_A3_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A0_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A0_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A0_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A0_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A1_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A1_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A1_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A1_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A2_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A2_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A2_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A2_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A3_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A3_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A3_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore4_A3_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A0_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A0_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A0_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A0_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A1_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A1_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A1_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A1_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A2_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A2_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A2_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A2_CASC3,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A3_CASC0,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A3_CASC1,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A3_CASC2,
                hls::stream<ap_axiu<64, 0, 0, 0>> &to_computeCore5_A3_CASC3);
