mkdir python_gold
cp output/06-python_gold/0-attention.self.query-bias.txt python_gold/
cp output/06-python_gold/0-attention.self.query-input.txt python_gold/
cp output/06-python_gold/0-attention.self.query-output.txt python_gold/
cp output/06-python_gold/0-attention.self.query-weight.txt python_gold/
cp output/06-python_gold/1-attention.self.key-bias.txt python_gold/
cp output/06-python_gold/1-attention.self.key-input.txt python_gold/
cp output/06-python_gold/1-attention.self.key-output.txt python_gold/
cp output/06-python_gold/1-attention.self.key-weight.txt python_gold/
cp output/06-python_gold/2-attention.self.value-bias.txt python_gold/
cp output/06-python_gold/2-attention.self.value-input.txt python_gold/
cp output/06-python_gold/2-attention.self.value-output.txt python_gold/
cp output/06-python_gold/2-attention.self.value-weight.txt python_gold/
cp output/06-python_gold/3-attention.output.dense-bias.txt python_gold/
cp output/06-python_gold/3-attention.output.dense-input.txt python_gold/
cp output/06-python_gold/3-attention.output.dense-output.txt python_gold/
cp output/06-python_gold/3-attention.output.dense-weight.txt python_gold/
cp output/06-python_gold/4-attention.output.LayerNorm-bias.txt python_gold/
cp output/06-python_gold/4-attention.output.LayerNorm-input.txt python_gold/
cp output/06-python_gold/4-attention.output.LayerNorm-output.txt python_gold/
cp output/06-python_gold/4-attention.output.LayerNorm-weight.txt python_gold/
cp output/06-python_gold/4-fused_dense1_norm1_output.txt python_gold/
cp output/06-python_gold/5-fused_norm1_dense2_bias.txt python_gold/
cp output/06-python_gold/5-fused_norm1_dense2_weight.txt python_gold/
cp output/06-python_gold/5-intermediate.dense-bias.txt python_gold/
cp output/06-python_gold/5-intermediate.dense-input.txt python_gold/
cp output/06-python_gold/5-intermediate.dense-output.txt python_gold/
cp output/06-python_gold/5-intermediate.dense-weight.txt python_gold/
cp output/06-python_gold/6-output.dense-bias.txt python_gold/
cp output/06-python_gold/6-output.dense-input.txt python_gold/
cp output/06-python_gold/6-output.dense-output.txt python_gold/
cp output/06-python_gold/6-output.dense-weight.txt python_gold/
cp output/06-python_gold/7-fused_dense3_norm2.txt python_gold/
cp output/06-python_gold/7-output.LayerNorm-bias.txt python_gold/
cp output/06-python_gold/7-output.LayerNorm-input.txt python_gold/
cp output/06-python_gold/7-output.LayerNorm-output.txt python_gold/
cp output/06-python_gold/7-output.LayerNorm-weight.txt python_gold/